### ISSUE TITLE
🐛 thumbnail buttons fail on Edge (on Windows)

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/Songhay.Player.YouTube#9]
![image](https://github.com/BryanWilhite/Songhay.Player.YouTube/assets/5226627/8ac3925f-652f-417f-a127-e89dd9b9ef3f)

```console
blazor.webassembly.js:1  crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Format_InvalidString
System.FormatException: Format_InvalidString
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus , TypeCode )
   at System.Number.ParseInt32(ReadOnlySpan`1 , NumberStyles , NumberFormatInfo )
   at System.Int32.Parse(String s, NumberStyles style, IFormatProvider provider)
   at Microsoft.FSharp.Core.LanguagePrimitives.ParseInt32(String s)
   at <StartupCode$Songhay-Player-YouTube>.$YtThumbsComponent.slideAsync@147-3.Invoke(String _arg9)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[Unit,String](AsyncActivation`1 ctxt, String result1, FSharpFunc`2 userCode)
   at Microsoft.FSharp.Control.AsyncPrimitives.Bind@589-1[[Microsoft.FSharp.Core.Unit, FSharp.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(String result1)
   at Microsoft.FSharp.Control.AsyncPrimitives.OnTaskCompleted[String](Task`1 completedTask, AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.AsyncPrimitives.AttachContinuationToTask@1249-1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(Unit unitVar0)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
window.Module.s.printErr @ blazor.webassembly.js:1
Te._internal.dotNetCriticalError @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.19.955cgpq4zc.js:1
$func219 @ dotnet.wasm:0x1a4c1
$func167 @ dotnet.wasm:0xce8f
$func166 @ dotnet.wasm:0xbd73
$func2815 @ dotnet.wasm:0xabf2c
$func1619 @ dotnet.wasm:0x6fcb4
$func1623 @ dotnet.wasm:0x70321
$mono_wasm_invoke_method @ dotnet.wasm:0x969f
Module._mono_wasm_invoke_method @ dotnet.6.0.19.955cgpq4zc.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.19.955cgpq4zc.js:1
$func219 @ dotnet.wasm:0x1a4c1
$func167 @ dotnet.wasm:0xce8f
$func166 @ dotnet.wasm:0xbd73
$func2815 @ dotnet.wasm:0xabf2c
$func1619 @ dotnet.wasm:0x6fcb4
$func1623 @ dotnet.wasm:0x70321
$mono_wasm_invoke_method @ dotnet.wasm:0x969f
Module._mono_wasm_invoke_method @ dotnet.6.0.19.955cgpq4zc.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:16
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.19.955cgpq4zc.js:1
$func219 @ dotnet.wasm:0x1a4c1
$func167 @ dotnet.wasm:0xce8f
$func166 @ dotnet.wasm:0xbd73
$func2815 @ dotnet.wasm:0xabf2c
$func1619 @ dotnet.wasm:0x6fcb4
$func1617 @ dotnet.wasm:0x6fc26
$func970 @ dotnet.wasm:0x50677
$func219 @ dotnet.wasm:0x1a47a
$func167 @ dotnet.wasm:0xce8f
$func166 @ dotnet.wasm:0xbd73
$func2815 @ dotnet.wasm:0xabf2c
$func1619 @ dotnet.wasm:0x6fcb4
$func1617 @ dotnet.wasm:0x6fc26
$func970 @ dotnet.wasm:0x50677
$func219 @ dotnet.wasm:0x1a47a
$func167 @ dotnet.wasm:0xce8f
$func166 @ dotnet.wasm:0xbd73
$func2815 @ dotnet.wasm:0xabf2c
$func1619 @ dotnet.wasm:0x6fcb4
$func1623 @ dotnet.wasm:0x70321
$mono_wasm_invoke_method @ dotnet.wasm:0x969f
Module._mono_wasm_invoke_method @ dotnet.6.0.19.955cgpq4zc.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet:19
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
b @ blazor.webassembly.js:1
invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
invokeWhenHeapUnlocked @ blazor.webassembly.js:1
S @ blazor.webassembly.js:1
C @ blazor.webassembly.js:1
dispatchGlobalEventToAllElements @ blazor.webassembly.js:1
onGlobalEvent @ blazor.webassembly.js:1
```

**Comment by BryanWilhite** [comment]
Microsoft updated Edge and fixed this issue.
